server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: root
      password: secret

  rabbitmq:
    host: localhost
#    port: 5672
#    username: myuser
#    password: secret

digidine:
  broker:
    exchange:
      orderNotificationExchange: digidine.order.notification
      productionNotificationExchange: digidine.order-production.notification
    key:
      orderNotificationKey: ms.order.notification
      orderProductionNotificationKey: ms.order-production.notification
    queue:
      order: digidine.order.notification.queue
      payment: digidine.payment.notification.queue
      production: digidine.production.notification.queue


