server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: root
      password: secret

  rabbitmq:
    host: localhost
#    port: 5672
#    username: myuser
#    password: secret
#
digidine:
  broker:
    exchange:
      orderNotificationExchange: digidine.order.notification
    key:
      orderNotificationKey: ms.order.notification
    queue: digidine.order.notification.queue

