name: full-security-scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Verify Java version
      run: java -version

    - name: Build the project
      run: mvn clean install
      # run: mvn clean install -DskipTests

    - name: SonarCloud
      uses: sonarsource/sonarqube-scan-action@v5.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.java.binaries=target/classes

    - name: Check SonarCloud Quality Gate
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=michelleamesquita_Order_Digidine" \
            | jq -r '.projectStatus.status')
          if [ "$STATUS" == "OK" ]; then
            echo "SonarCloud Quality Gate failed!"
            exit 1
          fi
      
    
